// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHgM-WNAJahnAXj0HS_awOEB3k1GUk41o',
    appId: '1:790961819225:web:b884d7e289e2a2dfef6b48',
    messagingSenderId: '790961819225',
    projectId: 'artful-fastness-364209',
    authDomain: 'artful-fastness-364209.firebaseapp.com',
    storageBucket: 'artful-fastness-364209.appspot.com',
    measurementId: 'G-MPZ31C4N15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4r3ujU26BRoATJn_tOvmT_oFByeYzTM',
    appId: '1:790961819225:android:a407cb9fb255d715ef6b48',
    messagingSenderId: '790961819225',
    projectId: 'artful-fastness-364209',
    storageBucket: 'artful-fastness-364209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWSLGX_rgt301m9NV31hC1IlLCFd2WZk8',
    appId: '1:790961819225:ios:2e03f253f42f6e40ef6b48',
    messagingSenderId: '790961819225',
    projectId: 'artful-fastness-364209',
    storageBucket: 'artful-fastness-364209.appspot.com',
    iosClientId: '790961819225-2jq4uop65h7algfa2lrep2p9q5ooqe94.apps.googleusercontent.com',
    iosBundleId: 'com.akdeveloper.tutorialsWallah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWSLGX_rgt301m9NV31hC1IlLCFd2WZk8',
    appId: '1:790961819225:ios:2e03f253f42f6e40ef6b48',
    messagingSenderId: '790961819225',
    projectId: 'artful-fastness-364209',
    storageBucket: 'artful-fastness-364209.appspot.com',
    iosClientId: '790961819225-2jq4uop65h7algfa2lrep2p9q5ooqe94.apps.googleusercontent.com',
    iosBundleId: 'com.akdeveloper.tutorialsWallah',
  );
}
