// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAAQBLaO-JjYRLxupopNZTFBCYsgg2a3w',
    appId: '1:760981735982:web:9b414cf32d477a4a4dadbf',
    messagingSenderId: '760981735982',
    projectId: 'tutorials-wallah',
    authDomain: 'tutorials-wallah.firebaseapp.com',
    storageBucket: 'tutorials-wallah.appspot.com',
    measurementId: 'G-BW9P49M1KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt6KM8RWVStAFgUH6qJHYBxvSJ7AKb41Y',
    appId: '1:760981735982:android:e42e22f410ca0f744dadbf',
    messagingSenderId: '760981735982',
    projectId: 'tutorials-wallah',
    storageBucket: 'tutorials-wallah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTkSNRb5L0uIm-Tu6FbhxdlXZquc2mrTE',
    appId: '1:760981735982:ios:f2a56197768ee1174dadbf',
    messagingSenderId: '760981735982',
    projectId: 'tutorials-wallah',
    storageBucket: 'tutorials-wallah.appspot.com',
    iosClientId: '760981735982-6aeth3o4brtq6ges5m0bnmqs84mtfno5.apps.googleusercontent.com',
    iosBundleId: 'com.akdeveloperz.tutorialsWallah',
  );
}
